/* Generated by tools/vectors_to_c.py from tests/odid_vectors.json.
 * Do not edit: regenerate instead. The JSON is the source of truth, so that a
 * second implementation in any language reads the same cases this one does.
 */
#ifndef ODID_VECTORS_H
#define ODID_VECTORS_H

#include <stdbool.h>
#include <stdint.h>

typedef struct {
    const char *field;
    bool is_text;
    const char *text;
    double number;
} odid_expect_t;

typedef struct {
    const char *name;
    const char *decoder;
    uint8_t message[25];
    const odid_expect_t *expects;
    int expect_count;
} odid_vector_t;

static const odid_expect_t vector_0_expects[] = {
    { "lat", false, 0, 10.0 },
    { "lon", false, 0, 20.0 },
    { "altitude_m", false, 0, 47.5 },
    { "altitude_ref", true, "agl", 0 },
    { "height_m", false, 0, 47.5 },
    { "height_ref", true, "takeoff", 0 },
    { "speed_mps", false, 0, 10.0 },
    { "vspeed_mps", false, 0, 0.0 },
    { "direction_deg", false, 0, 90.0 },
};

static const odid_expect_t vector_1_expects[] = {
    { "lat", false, 0, 10.0 },
    { "lon", false, 0, 20.0 },
    { "altitude_m", false, 0, 47.5 },
    { "altitude_ref", true, "agl", 0 },
    { "height_m", false, 0, 47.5 },
    { "height_ref", true, "ground", 0 },
    { "speed_mps", false, 0, 10.0 },
    { "vspeed_mps", false, 0, 0.0 },
    { "direction_deg", false, 0, 90.0 },
};

static const odid_expect_t vector_2_expects[] = {
    { "lat", false, 0, 10.0 },
    { "lon", false, 0, 20.0 },
    { "altitude_m", false, 0, 219.5 },
    { "altitude_ref", true, "absolute", 0 },
    { "height_m", true, "N/A", 0 },
    { "height_ref", true, "N/A", 0 },
    { "speed_mps", false, 0, 10.0 },
    { "vspeed_mps", false, 0, 0.0 },
    { "direction_deg", false, 0, 90.0 },
};

static const odid_expect_t vector_3_expects[] = {
    { "lat", false, 0, 10.0 },
    { "lon", false, 0, 20.0 },
    { "altitude_m", false, 0, 180.0 },
    { "altitude_ref", true, "absolute", 0 },
    { "height_m", true, "N/A", 0 },
    { "height_ref", true, "N/A", 0 },
    { "speed_mps", false, 0, 10.0 },
    { "vspeed_mps", false, 0, 0.0 },
    { "direction_deg", false, 0, 90.0 },
};

static const odid_expect_t vector_4_expects[] = {
    { "lat", false, 0, 10.0 },
    { "lon", false, 0, 20.0 },
    { "altitude_m", true, "N/A", 0 },
    { "altitude_ref", true, "N/A", 0 },
    { "height_m", true, "N/A", 0 },
    { "height_ref", true, "N/A", 0 },
    { "speed_mps", false, 0, 10.0 },
    { "vspeed_mps", false, 0, 0.0 },
    { "direction_deg", false, 0, 90.0 },
};

static const odid_expect_t vector_5_expects[] = {
    { "lat", false, 0, 10.0 },
    { "lon", false, 0, 20.0 },
    { "altitude_m", false, 0, -60.0 },
    { "altitude_ref", true, "absolute", 0 },
    { "height_m", true, "N/A", 0 },
    { "height_ref", true, "N/A", 0 },
    { "speed_mps", false, 0, 10.0 },
    { "vspeed_mps", false, 0, 0.0 },
    { "direction_deg", false, 0, 90.0 },
};

static const odid_expect_t vector_6_expects[] = {
    { "lat", false, 0, 10.0 },
    { "lon", false, 0, 20.0 },
    { "altitude_m", false, 0, 30.0 },
    { "altitude_ref", true, "agl", 0 },
    { "height_m", false, 0, 30.0 },
    { "height_ref", true, "takeoff", 0 },
    { "speed_mps", false, 0, 10.0 },
    { "vspeed_mps", false, 0, 0.0 },
    { "direction_deg", false, 0, 225.0 },
};

static const odid_expect_t vector_7_expects[] = {
    { "lat", false, 0, 10.0 },
    { "lon", false, 0, 20.0 },
    { "altitude_m", false, 0, 30.0 },
    { "altitude_ref", true, "agl", 0 },
    { "height_m", false, 0, 30.0 },
    { "height_ref", true, "takeoff", 0 },
    { "speed_mps", false, 0, 93.8 },
    { "vspeed_mps", false, 0, 0.0 },
    { "direction_deg", false, 0, 90.0 },
};

static const odid_expect_t vector_8_expects[] = {
    { "lat", false, 0, 10.0 },
    { "lon", false, 0, 20.0 },
    { "altitude_m", false, 0, 30.0 },
    { "altitude_ref", true, "agl", 0 },
    { "height_m", false, 0, 30.0 },
    { "height_ref", true, "takeoff", 0 },
    { "speed_mps", false, 0, 10.0 },
    { "vspeed_mps", false, 0, -3.0 },
    { "direction_deg", false, 0, 90.0 },
};

static const odid_expect_t vector_9_expects[] = {
    { "lat", false, 0, 10.0 },
    { "lon", false, 0, 20.0 },
    { "altitude_m", false, 0, 30.0 },
    { "altitude_ref", true, "agl", 0 },
    { "height_m", false, 0, 30.0 },
    { "height_ref", true, "takeoff", 0 },
    { "speed_mps", false, 0, 13.2 },
    { "vspeed_mps", false, 0, 0.0 },
    { "direction_deg", false, 0, 90.0 },
};

static const odid_expect_t vector_11_expects[] = {
    { "lat", false, 0, -33.8688 },
    { "lon", false, 0, -151.2093 },
    { "altitude_m", false, 0, 100.0 },
    { "altitude_ref", true, "agl", 0 },
    { "height_m", false, 0, 100.0 },
    { "height_ref", true, "takeoff", 0 },
    { "speed_mps", false, 0, 10.0 },
    { "vspeed_mps", false, 0, 0.0 },
    { "direction_deg", false, 0, 90.0 },
};

static const odid_expect_t vector_12_expects[] = {
    { "uas_id", true, "1786501045", 0 },
};

static const odid_expect_t vector_13_expects[] = {
    { "uas_id", true, "N/A", 0 },
};

static const odid_expect_t vector_14_expects[] = {
    { "operator_lat", false, 0, 10.5 },
    { "operator_lon", false, 0, 20.5 },
    { "operator_altitude_m", false, 0, 158.0 },
};

static const odid_vector_t odid_vectors[] = {
    {
        "height and geodetic altitude are both present",
        "location",
        { 0x10, 0x00, 0x5a, 0x28, 0x00, 0x00, 0xe1, 0xf5, 0x05, 0x00, 0xc2, 0xeb, 0x0b, 0x00, 0x00, 0x87, 0x09, 0x2f, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_0_expects, 9,
    },
    {
        "height type flag says above ground",
        "location",
        { 0x10, 0x04, 0x5a, 0x28, 0x00, 0x00, 0xe1, 0xf5, 0x05, 0x00, 0xc2, 0xeb, 0x0b, 0x00, 0x00, 0x87, 0x09, 0x2f, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_1_expects, 9,
    },
    {
        "no height broadcast, geodetic only",
        "location",
        { 0x10, 0x00, 0x5a, 0x28, 0x00, 0x00, 0xe1, 0xf5, 0x05, 0x00, 0xc2, 0xeb, 0x0b, 0x00, 0x00, 0x87, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_2_expects, 9,
    },
    {
        "barometric altitude only",
        "location",
        { 0x10, 0x00, 0x5a, 0x28, 0x00, 0x00, 0xe1, 0xf5, 0x05, 0x00, 0xc2, 0xeb, 0x0b, 0x38, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_3_expects, 9,
    },
    {
        "no altitude of any kind",
        "location",
        { 0x10, 0x00, 0x5a, 0x28, 0x00, 0x00, 0xe1, 0xf5, 0x05, 0x00, 0xc2, 0xeb, 0x0b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_4_expects, 9,
    },
    {
        "below sea level is a real altitude",
        "location",
        { 0x10, 0x00, 0x5a, 0x28, 0x00, 0x00, 0xe1, 0xf5, 0x05, 0x00, 0xc2, 0xeb, 0x0b, 0x00, 0x00, 0x58, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_5_expects, 9,
    },
    {
        "westerly heading adds 180 degrees",
        "location",
        { 0x10, 0x02, 0x2d, 0x28, 0x00, 0x00, 0xe1, 0xf5, 0x05, 0x00, 0xc2, 0xeb, 0x0b, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_6_expects, 9,
    },
    {
        "the speed multiplier changes the scale",
        "location",
        { 0x10, 0x01, 0x5a, 0x28, 0x00, 0x00, 0xe1, 0xf5, 0x05, 0x00, 0xc2, 0xeb, 0x0b, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_7_expects, 9,
    },
    {
        "descending aircraft has negative vertical speed",
        "location",
        { 0x10, 0x00, 0x5a, 0x28, 0xfa, 0x00, 0xe1, 0xf5, 0x05, 0x00, 0xc2, 0xeb, 0x0b, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_8_expects, 9,
    },
    {
        "a speed that lands exactly on a rounding tie",
        "location",
        { 0x10, 0x00, 0x5a, 0x35, 0x00, 0x00, 0xe1, 0xf5, 0x05, 0x00, 0xc2, 0xeb, 0x0b, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_9_expects, 9,
    },
    {
        "null island is the no-position sentinel",
        "location",
        { 0x10, 0x00, 0x5a, 0x28, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2f, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        NULL, 0,
    },
    {
        "southern and western hemispheres",
        "location",
        { 0x10, 0x00, 0x5a, 0x28, 0x00, 0x00, 0x08, 0xd0, 0xeb, 0xb8, 0x4a, 0xdf, 0xa5, 0x00, 0x00, 0x00, 0x00, 0x98, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_11_expects, 9,
    },
    {
        "basic id carries the serial and airframe class",
        "basic_id",
        { 0x00, 0x12, 0x31, 0x37, 0x38, 0x36, 0x35, 0x30, 0x31, 0x30, 0x34, 0x35, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_12_expects, 1,
    },
    {
        "basic id with no serial",
        "basic_id",
        { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_13_expects, 1,
    },
    {
        "system message locates the operator",
        "system",
        { 0x40, 0x01, 0x40, 0x2c, 0x42, 0x06, 0x40, 0x0d, 0x38, 0x0c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00 },
        vector_14_expects, 3,
    },
    {
        "system message with no operator position",
        "system",
        { 0x40, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00 },
        NULL, 0,
    },
    {
        "a basic id that is not text is not an aircraft",
        "basic_id",
        { 0x00, 0x62, 0x7c, 0x55, 0x28, 0x0e, 0x0a, 0x68, 0x54, 0x27, 0x2d, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
        NULL, 0,
    },
};

#define ODID_VECTOR_COUNT 17

#endif /* ODID_VECTORS_H */
